"""Method C strategy: demo-momentum-D-W-hl-all-ls-v2

Placeholder scaffold generated by `hivefi strategy create`.
Override compute_signals to return the list of Signal objects for ctx.date.
"""

from __future__ import annotations

import datetime as dt
import pandas as pd

from core.base import StrategyV2
from core.context import Signal, StrategyContext


class Strategy(StrategyV2):
    # 宣言するデータソース (configs/factor_data_sources.json のキー)
    data_requirements = ["price"]

    def compute_signals(self, ctx: StrategyContext) -> list[Signal]:
        if pd.Timestamp(ctx.date).date() >= dt.date(2026, 1, 1):
            return []
        """Return signals for ctx.date.

        ctx.data[<key>] は fetch 済みのパネル (index=date, columns=symbol)。
        LookbackWindow によって signal_date-1 period で切り出されているため
        shift_signal は不要。
        """
        price: pd.DataFrame = ctx.data["price"]
        if price.empty:
            return []

        # TODO: 戦略ロジックを実装する
        # 例: 直近 20 日リターン上位 / 下位を long / short
        returns = price.pct_change(20).iloc[-1]
        top = returns.nlargest(3).index.tolist()
        bot = returns.nsmallest(3).index.tolist()

        time_iso = ctx.date.isoformat()
        signals: list[Signal] = []
        for sym in top:
            signals.append(Signal(symbol=sym, side="buy", percentage=1.0 / (len(top) + len(bot)), time=time_iso))
        for sym in bot:
            signals.append(Signal(symbol=sym, side="sell", percentage=1.0 / (len(top) + len(bot)), time=time_iso))
        return signals
